# Generated by Django 6.0 on 2025-12-23 09:40

import apps.portfolio.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Resume file (PDF or image)', upload_to=apps.portfolio.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('ocr_confidence', models.FloatField(blank=True, help_text='OCR confidence score (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('ocr_processing', 'OCR Processing'), ('ai_analysis', 'AI Analysis'), ('component_selection', 'Component Selection'), ('layout_generation', 'Layout Generation'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Processing progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status_message', models.CharField(blank=True, default='', max_length=255)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('candidate_title', models.CharField(blank=True, default='', max_length=255)),
                ('professional_category', models.CharField(choices=[('creative', 'Creative'), ('technical', 'Technical'), ('corporate', 'Corporate'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI analysis confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('selected_theme', models.CharField(choices=[('neon_blue', 'Neon Blue'), ('emerald_green', 'Emerald Green'), ('cyber_pink', 'Cyber Pink')], default='neon_blue', max_length=20)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_result', to='portfolio.resume')),
            ],
            options={
                'verbose_name': 'Processing Result',
                'verbose_name_plural': 'Processing Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('tool_hero_prism', 'Hero Prism'), ('tool_hero_terminal', 'Hero Terminal'), ('tool_exp_timeline', 'Experience Timeline'), ('tool_exp_masonry', 'Experience Masonry'), ('tool_skills_dots', 'Skills Dots'), ('tool_skills_radar', 'Skills Radar'), ('tool_stats_bento', 'Stats Bento')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the component')),
                ('props', models.JSONField(blank=True, default=dict, help_text='Component-specific configuration props')),
                ('theme', models.CharField(blank=True, default='', help_text='Component-specific theme override', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_selections', to='portfolio.processingresult')),
            ],
            options={
                'verbose_name': 'Component Selection',
                'verbose_name_plural': 'Component Selections',
                'ordering': ['order'],
                'unique_together': {('processing_result', 'order')},
            },
        ),
    ]
